apiVersion: v1
name: cluster-registry
description: Cluster registry controller for K8s
home: https://eti.cisco.com/

maintainers:
  - email: ciscoeti@cisco.com
    name: Cisco
sources:
  - https://github.com/cisco-open/cluster-registry-controller

version: 0.2.11
appVersion: v0.2.11
